import google.generativeai as genai
import os
import json
from dotenv import load_dotenv

load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY", ""))

SYSTEM_PROMPT = """You are CareBot, a knowledgeable AI health assistant. You help users with:
- Symptom assessment and possible conditions
- Physical pain guidance (neck, back, shoulder, knee, wrist, etc.)
- Mental wellness and stress management
- General health questions
- Nutrition and lifestyle advice

Rules:
- Never diagnose with certainty. Use language like "may suggest", "could indicate", "commonly associated with"
- Never prescribe specific medicines by name
- Recommend consulting a doctor for serious concerns
- Be warm, clear, and concise
- When user describes symptoms or pain, ask 1-2 clarifying questions if needed
- Suggest practical, actionable advice

At the start of a conversation, greet and suggest what users can ask about."""

EMERGENCY_KEYWORDS = [
    "chest pain", "difficulty breathing", "can't breathe", "cant breathe",
    "stroke", "severe bleeding", "loss of consciousness", "unconscious",
    "seizure", "heart attack", "not breathing", "choking", "anaphylaxis",
    "suicidal", "want to die", "kill myself", "overdose"
]

def check_emergency(text: str) -> bool:
    lower = text.lower()
    return any(kw in lower for kw in EMERGENCY_KEYWORDS)

def _call_gemini(messages: list) -> str:
    try:
        model = genai.GenerativeModel("gemini-2.5-flash", system_instruction=SYSTEM_PROMPT)
        chat = model.start_chat(history=messages[:-1] if len(messages) > 1 else [])
        response = chat.send_message(messages[-1]["parts"])
        return response.text.strip()
    except Exception:
        return "I'm having trouble connecting right now. Please try again in a moment."

def chat_response(conversation_history: list, new_message: str) -> str:
    if check_emergency(new_message):
        return ("🚨 **This sounds like a potential medical emergency.**\n\n"
                "Please **call emergency services (112/911) immediately** or go to the nearest emergency room.\n\n"
                "Do not wait. Your safety is the priority.")
    
    gemini_history = []
    for msg in conversation_history[-8:]:
        gemini_history.append({"role": msg["role"], "parts": msg["content"]})
    gemini_history.append({"role": "user", "parts": new_message})
    
    return _call_gemini(gemini_history)

def generate_report_data(conversation_history: list, user_name: str) -> dict:
    convo_text = "\n".join([
        f"{'Patient' if m['role'] == 'user' else 'CareBot'}: {m['content']}"
        for m in conversation_history
    ])

    prompt = f"""Based on this health conversation with {user_name}, generate a comprehensive structured health report.

CONVERSATION:
{convo_text}

Generate a JSON report with EXACTLY this structure (no markdown, pure JSON):
{{
  "report_title": "specific title based on main health concern discussed",
  "summary": "2-3 sentence overview of the health discussion",
  "main_concerns": [
    {{"issue": "concern name", "description": "detailed explanation of this health issue", "severity": "Mild/Moderate/Needs Attention"}}
  ],
  "possible_conditions": ["condition 1", "condition 2", "condition 3"],
  "suggestions": [
    {{"title": "suggestion title", "detail": "specific actionable detail"}}
  ],
  "activities_and_yoga": [
    {{"name": "exercise/yoga name", "instructions": "how to do it", "duration": "how long/how many times", "benefit": "what it helps"}}
  ],
  "what_to_avoid": [
    {{"item": "thing to avoid", "reason": "why to avoid it"}}
  ],
  "what_to_follow": [
    {{"habit": "healthy habit", "detail": "specific instruction"}}
  ],
  "diet_plan": {{
    "overview": "brief diet philosophy for this condition",
    "morning": ["item 1", "item 2"],
    "midmorning": ["item 1"],
    "lunch": ["item 1", "item 2"],
    "evening": ["item 1"],
    "dinner": ["item 1", "item 2"],
    "foods_to_include": ["food 1", "food 2", "food 3", "food 4"],
    "foods_to_avoid": ["food 1", "food 2", "food 3"]
  }},
  "when_to_see_doctor": ["specific sign 1", "specific sign 2", "specific sign 3"],
  "disclaimer": "This report is generated by AI for informational purposes only and does not constitute medical diagnosis or treatment."
}}

Be specific and detailed. Base everything strictly on what was discussed. Return ONLY valid JSON."""

    try:
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt)
        text = response.text.strip()
        text = text.replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as e:
        return {
            "report_title": "Health Assessment Report",
            "summary": "A health consultation was conducted covering the topics discussed in your session.",
            "main_concerns": [{"issue": "Health Consultation", "description": "General health discussion", "severity": "Mild"}],
            "possible_conditions": ["To be assessed by a physician"],
            "suggestions": [{"title": "Consult a Doctor", "detail": "Please visit a qualified healthcare professional for a thorough evaluation."}],
            "activities_and_yoga": [{"name": "Walking", "instructions": "30 minutes daily walk at moderate pace", "duration": "30 min/day", "benefit": "Improves overall health"}],
            "what_to_avoid": [{"item": "Self-medication", "reason": "Always consult a doctor before taking any medication"}],
            "what_to_follow": [{"habit": "Regular check-ups", "detail": "Schedule routine health check-ups with your doctor"}],
            "diet_plan": {
                "overview": "Maintain a balanced, nutritious diet",
                "morning": ["Warm water with lemon", "Oats or whole grain cereal"],
                "midmorning": ["Fresh fruit or nuts"],
                "lunch": ["Balanced meal with protein, vegetables, and whole grains"],
                "evening": ["Herbal tea", "Light snack"],
                "dinner": ["Light, easily digestible meal", "Salad or soup"],
                "foods_to_include": ["Fresh vegetables", "Whole grains", "Lean protein", "Fresh fruits"],
                "foods_to_avoid": ["Processed foods", "Excessive sugar", "Fried foods"]
            },
            "when_to_see_doctor": ["Symptoms worsen or persist beyond 3 days", "Fever above 103°F", "Difficulty breathing"],
            "disclaimer": "This report is generated by AI for informational purposes only and does not constitute medical diagnosis or treatment."
        }
